In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
from tqdm import tqdm_notebook

In [3]:
mlinkdf = pd.read_csv("./data/ChaoSun_Rpt_Sep2016.csv")

In [4]:
silodf = pd.read_csv('./data/full-link-mlink-count-primary.csv')

In [5]:
mlinkdf[['Volume','Flow']]

         Volume    Flow
0          23.0    92.0
1          35.0   420.0
2         101.0  1212.0
3          45.0   540.0
4          46.0   552.0
5          29.0   348.0
6          42.0   504.0
7          42.0   168.0
8          36.0   144.0
9          28.0   336.0
10         28.0   336.0
11         16.0   192.0
12         16.0   192.0
13         18.0   216.0
14         23.0   276.0
15         25.0   300.0
16         10.0   120.0
17         10.0     NaN
18          7.0    84.0
19         11.0   132.0
20         12.0   144.0
21         13.0   156.0
22         11.0   132.0
23         16.0   192.0
24         10.0   120.0
25         14.0   168.0
26         14.0   168.0
27         19.0    76.0
28         24.0    96.0
29         45.0   540.0
...         ...     ...
2842530    23.0   276.0
2842531   144.0  1728.0
2842532   131.0  1572.0
2842533   130.0  1560.0
2842534   128.0  1536.0
2842535   127.0  1524.0
2842536   127.0  1524.0
2842537    72.0   864.0
2842538    70.0   840.0
2842539    70.0   840.0
2842540    61.0   732.0
2842541    69.0   828.0
2842542    72.0   864.0
2842543    42.0   504.0
2842544    33.0   396.0
2842545    16.0   192.0
2842546    27.0   324.0
2842547    22.0   264.0
2842548    27.0   324.0
2842549    28.0   336.0
2842550    42.0   504.0
2842551    41.0   492.0
2842552    38.0   456.0
2842553    41.0   492.0
2842554    96.0  1152.0
2842555    99.0  1188.0
2842556    96.0  1152.0
2842557   120.0  1440.0
2842558   120.0     NaN
2842559   125.0     NaN

[2842560 rows x 2 columns]

In [6]:
mlinkdf.columns

Index(['ID', 'M_Link_ID', 'localDate', 'localTime', 'Ext1_Speed',
       'Ext1_Speed_Samples', 'Ext1_Speed_Quality', 'NPI_Speed',
       'NPI_Speed_Quality', 'Speed', 'Speed_Method', 'SCATS_Volume',
       'SCATS_Volume_Quality', 'NPI_Volume', 'NPI_Volume_Quality', 'Volume',
       'Volume_Method', 'NPI_Occupancy', 'NPI_Occupancy_Quality', 'SCATS_DS',
       'SCATS_CM', 'SCATS_Flow', 'Flow', 'Flow_Method', 'Lanes', 'IRIS_Speed',
       'IRIS_Speed_Quality', 'IRIS_Volume', 'IRIS_Volume_Quality',
       'Ext1_Speed_Median', 'SCATS_Factor'],
      dtype='object')

In [7]:
silodf

,Link Id,Hour,MATSIM volumes,mlink,Sub-Area_Name,Route_No,Route_Name,Peak,Direction,Road_Number,...,To_Int,weight,Avg_Posted_Speed,Start_SLK,End_SLK,IRIS_Link_ID,from_node,to_node,Link_Type,polyline
0,1000,1,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
1,1000,2,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
2,1000,3,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
3,1000,4,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
4,1000,5,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
5,1000,6,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
6,1000,7,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
7,1000,8,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
8,1000,9,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
9,1000,10,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
10,1000,11,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
11,1000,12,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
12,1000,13,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
13,1000,14,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
14,1000,15,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
15,1000,16,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
16,1000,17,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
17,1000,18,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
18,1000,19,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
19,1000,20,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
20,1000,21,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
21,1000,22,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
22,1000,23,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
23,1000,24,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
24,1001,1,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
25,1001,2,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
26,1001,3,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
27,1001,4,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
28,1001,5,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
29,1001,6,0,604,South West,16,Melville Mandurah Hwy,Outbound,Southbound,H002,...,Dixon Rd,1050,80,26.44,27.49,CC-SW-16/19-L,4143,4317,Art,"LINESTRING (115.755349 -32.268469, 115.755548 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148266,888,19,0,705,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Karnup Off,6590,110,54.12,47.53,CC-SW-18/36-R,171977,171971,Fwy,"LINESTRING (115.80746 -32.431213, 115.809851 -..."
148267,888,20,0,705,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Karnup Off,6590,110,54.12,47.53,CC-SW-18/36-R,171977,171971,Fwy,"LINESTRING (115.80746 -32.431213, 115.809851 -..."
148268,888,21,0,705,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Karnup Off,6590,110,54.12,47.53,CC-SW-18/36-R,171977,171971,Fwy,"LINESTRING (115.80746 -32.431213, 115.809851 -..."
148269,888,22,0,705,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Karnup Off,6590,110,54.12,47.53,CC-SW-18/36-R,171977,171971,Fwy,"LINESTRING (115.80746 -32.431213, 115.809851 -..."
148270,888,23,0,705,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Karnup Off,6590,110,54.12,47.53,CC-SW-18/36-R,171977,171971,Fwy,"LINESTRING (115.80746 -32.431213, 115.809851 -..."
148271,888,24,0,705,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Karnup Off,6590,110,54.12,47.53,CC-SW-18/36-R,171977,171971,Fwy,"LINESTRING (115.80746 -32.431213, 115.809851 -..."
148272,890,1,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148273,890,2,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148274,890,3,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148275,890,4,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148276,890,5,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148277,890,6,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148278,890,7,22,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148279,890,8,20,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148280,890,9,17,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148281,890,10,1,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148282,890,11,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148283,890,12,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148284,890,13,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148285,890,14,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148286,890,15,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148287,890,16,17,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148288,890,17,16,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148289,890,18,24,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148290,890,19,3,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148291,890,20,3,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148292,890,21,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148293,890,22,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148294,890,23,0,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."
148295,890,24,2,707,South West,18,Kwinana Fwy,Inbound,Northbound,H015,...,Safety Bay Off,4330,110,46.69,42.36,CC-SW-18/34-R,171972,171993,Fwy,"LINESTRING (115.833122 -32.369005, 115.83332 -..."

In [8]:
mlinkdf['hour'] = mlinkdf.localTime.apply(lambda x: int(x.split(':')[0]))
mlinkdf['date'] = mlinkdf.localDate.apply(lambda x: int(x.split('-')[-1]))

In [9]:
mdf = mlinkdf[['M_Link_ID', 'date','hour','Volume']]
mdf.columns = ['mlink','date','hour','volume']

In [11]:
mlinkdf

,ID,M_Link_ID,localDate,localTime,Ext1_Speed,Ext1_Speed_Samples,Ext1_Speed_Quality,NPI_Speed,NPI_Speed_Quality,Speed,...,Flow_Method,Lanes,IRIS_Speed,IRIS_Speed_Quality,IRIS_Volume,IRIS_Volume_Quality,Ext1_Speed_Median,SCATS_Factor,hour,date
0,126999649,76,2016-09-01,00:00:00.0,56.49,7,1,NaN,NaN,61.50,...,0,3,61.5,1,23.0,1,59.40,1.35,0,1
1,126999650,77,2016-09-01,00:00:00.0,21.63,2,1,NaN,NaN,21.63,...,0,5,NaN,0,NaN,0,22.07,1.00,0,1
2,126999651,78,2016-09-01,00:00:00.0,40.81,2,1,NaN,NaN,40.81,...,0,4,NaN,0,NaN,0,37.20,1.00,0,1
3,126999652,79,2016-09-01,00:00:00.0,32.82,7,1,NaN,NaN,32.82,...,0,2,NaN,0,NaN,0,42.32,1.00,0,1
4,126999653,80,2016-09-01,00:00:00.0,35.81,10,1,NaN,NaN,35.81,...,0,3,NaN,0,NaN,0,56.92,1.00,0,1
5,126999654,81,2016-09-01,00:00:00.0,60.49,7,1,NaN,NaN,60.49,...,0,2,NaN,0,NaN,0,59.93,1.00,0,1
6,126999655,82,2016-09-01,00:00:00.0,60.11,2,1,NaN,NaN,60.11,...,0,2,NaN,0,NaN,0,57.89,1.00,0,1
7,126999656,83,2016-09-01,00:00:00.0,60.45,1,1,NaN,NaN,52.00,...,0,3,52.0,1,42.0,1,60.45,1.13,0,1
8,126999657,84,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,59.60,...,0,3,59.6,1,36.0,1,0.00,0.97,0,1
9,126999658,85,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,59.00,...,0,3,NaN,0,NaN,0,0.00,1.00,0,1
10,126999659,86,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,56.39,...,0,3,NaN,0,NaN,0,0.00,1.00,0,1
11,126999660,87,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,51.95,...,0,2,NaN,0,NaN,0,0.00,1.00,0,1
12,126999661,88,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,55.30,...,0,2,NaN,0,NaN,0,0.00,1.00,0,1
13,126999662,89,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,54.00,...,0,2,NaN,0,NaN,0,0.00,1.00,0,1
14,126999663,90,2016-09-01,00:00:00.0,56.17,2,1,NaN,NaN,56.17,...,0,2,NaN,0,NaN,0,57.88,1.00,0,1
15,126999664,91,2016-09-01,00:00:00.0,58.30,6,1,NaN,NaN,58.30,...,0,2,NaN,0,NaN,0,59.41,1.00,0,1
16,126999665,92,2016-09-01,00:00:00.0,54.99,3,1,NaN,NaN,54.99,...,0,1,NaN,0,NaN,0,53.75,1.00,0,1
17,126999666,93,2016-09-01,00:00:00.0,61.17,2,1,NaN,NaN,61.17,...,0,2,NaN,0,NaN,0,61.78,NaN,0,1
18,126999667,94,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,46.24,...,0,2,NaN,0,NaN,0,0.00,1.00,0,1
19,126999668,95,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,45.59,...,0,2,NaN,0,NaN,0,0.00,1.00,0,1
20,126999669,96,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,58.28,...,0,3,NaN,0,NaN,0,0.00,1.00,0,1
21,126999670,97,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,58.17,...,0,3,NaN,0,NaN,0,0.00,1.00,0,1
22,126999671,98,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,52.88,...,0,3,NaN,0,NaN,0,0.00,1.00,0,1
23,126999672,99,2016-09-01,00:00:00.0,0.00,0,0,NaN,NaN,51.00,...,0,2,NaN,0,NaN,0,0.00,1.00,0,1
24,126999673,100,2016-09-01,00:00:00.0,51.42,4,1,NaN,NaN,51.42,...,0,2,NaN,0,NaN,0,54.27,1.00,0,1
25,126999674,101,2016-09-01,00:00:00.0,43.62,2,1,NaN,NaN,43.62,...,0,3,NaN,0,NaN,0,44.34,1.00,0,1
26,126999675,102,2016-09-01,00:00:00.0,52.85,6,1,NaN,NaN,52.85,...,0,2,NaN,0,NaN,0,56.27,1.00,0,1
27,126999676,103,2016-09-01,00:00:00.0,55.05,8,1,NaN,NaN,58.10,...,0,3,58.1,1,19.0,1,56.97,1.00,0,1
28,126999677,104,2016-09-01,00:00:00.0,31.18,9,1,NaN,NaN,54.30,...,0,2,54.3,1,24.0,1,35.81,0.77,0,1
29,126999678,105,2016-09-01,00:00:00.0,40.20,8,1,NaN,NaN,40.20,...,0,3,NaN,0,NaN,0,56.84,1.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2842530,129842179,1081,2016-09-30,23:45:00.0,42.93,5,1,NaN,NaN,42.93,...,0,2,NaN,0,NaN,0,43.13,1.00,23,30
2842531,129842180,1082,2016-09-30,23:45:00.0,59.11,25,1,NaN,NaN,59.11,...,0,3,NaN,0,NaN,0,63.18,1.00,23,30
2842532,129842181,1083,2016-09-30,23:45:00.0,59.21,46,1,NaN,NaN,59.21,...,0,3,NaN,0,NaN,0,62.16,1.00,23,30
2842533,129842182,1084,2016-09-30,23:45:00.0,45.69,18,1,NaN,NaN,45.69,...,0,3,NaN,0,NaN,0,56.81,1.00,23,30
2842534,129842183,1085,2016-09-30,23:45:00.0,54.55,20,1,NaN,NaN,54.55,...,0,3,NaN,0,NaN,0,60.78,1.00,23,30
2842535,129842184,1086,2016-09-30,23:45:00.0,53.07,21,1,NaN,NaN,53.07,...,0,4,NaN,0,NaN,0,60.78,1.00,23,30
2842536,129842185,1087,2016-09-30,23:45:00.0,50.55,4,1,NaN,NaN,50.55,...,0,4,NaN,0,NaN,0,55.46,1.00,23,30
2842537,129842186,1088,2016-09-30,23:45:00.0,54.09,2,1,NaN,NaN,54.09,...,0,3,NaN,0,NaN,0,56.99,1.00,23,30
2842538,129842187,1089,2016-09-30,23:45:00.0,56.88,5,1,NaN,NaN,56.88,...,0,3,NaN,0,NaN,0,56.49,1.00,23,30
2842539,129842188,1090,2016-09-30,23:45:00.0,48.79,4,1,NaN,NaN,48.79,...,0,3,NaN,0,NaN,0,51.12,1.00,23,30
2842540,129842189,1091,2016-09-30,23:45:00.0,61.52,11,1,NaN,NaN,61.52,...,0,3,NaN,0,NaN,0,64.69,1.00,23,30
2842541,129842190,1092,2016-09-30,23:45:00.0,40.34,11,1,NaN,NaN,40.34,...,0,4,NaN,0,NaN,0,63.18,1.00,23,30
2842542,129842191,1093,2016-09-30,23:45:00.0,56.10,6,1,NaN,NaN,56.10,...,0,4,NaN,0,NaN,0,60.69,1.00,23,30
2842543,129842192,1094,2016-09-30,23:45:00.0,49.79,8,1,NaN,NaN,49.79,...,0,2,NaN,0,NaN,0,53.84,1.00,23,30
2842544,129842193,1095,2016-09-30,23:45:00.0,55.16,8,1,NaN,NaN,55.16,...,0,3,NaN,0,NaN,0,64.12,1.00,23,30
2842545,129842194,1096,2016-09-30,23:45:00.0,0.00,0,0,NaN,NaN,55.25,...,0,3,NaN,0,NaN,0,0.00,1.00,23,30
2842546,129842195,1097,2016-09-30,23:45:00.0,0.00,0,0,NaN,NaN,55.44,...,0,4,NaN,0,NaN,0,0.00,1.00,23,30
2842547,129842196,1098,2016-09-30,23:45:00.0,0.00,0,0,NaN,NaN,50.00,...,0,4,NaN,0,NaN,0,0.00,1.00,23,30
2842548,129842197,1099,2016-09-30,23:45:00.0,60.73,7,1,NaN,NaN,60.73,...,0,3,NaN,0,NaN,0,66.51,1.00,23,30
2842549,129842198,1100,2016-09-30,23:45:00.0,66.38,13,1,NaN,NaN,66.38,...,0,3,NaN,0,NaN,0,66.51,1.00,23,30
2842550,129842199,1101,2016-09-30,23:45:00.0,49.03,9,1,NaN,NaN,49.03,...,0,3,NaN,0,NaN,0,45.17,1.00,23,30
2842551,129842200,1102,2016-09-30,23:45:00.0,35.44,5,1,NaN,NaN,35.44,...,0,3,NaN,0,NaN,0,52.72,1.00,23,30
2842552,129842201,1103,2016-09-30,23:45:00.0,51.46,14,1,NaN,NaN,51.46,...,0,4,NaN,0,NaN,0,52.56,1.00,23,30
2842553,129842202,1104,2016-09-30,23:45:00.0,24.55,11,1,NaN,NaN,24.55,...,0,3,NaN,0,NaN,0,25.35,1.00,23,30
2842554,129842203,1105,2016-09-30,23:45:00.0,44.42,24,1,NaN,NaN,44.42,...,0,3,NaN,0,NaN,0,50.27,1.00,23,30
2842555,129842204,1106,2016-09-30,23:45:00.0,44.76,16,1,NaN,NaN,44.76,...,0,3,NaN,0,NaN,0,47.73,1.00,23,30
2842556,129842205,1107,2016-09-30,23:45:00.0,42.05,13,1,NaN,NaN,42.05,...,0,2,NaN,0,NaN,0,51.61,1.00,23,30
2842557,129842206,1108,2016-09-30,23:45:00.0,58.51,28,1,NaN,NaN,58.51,...,0,3,NaN,0,NaN,0,61.94,1.00,23,30
2842558,129842207,1109,2016-09-30,23:45:00.0,63.17,14,1,NaN,NaN,63.17,...,0,2,NaN,0,NaN,0,66.00,NaN,23,30
2842559,129842208,1110,2016-09-30,23:45:00.0,97.16,16,17,NaN,NaN,95.00,...,0,3,NaN,0,NaN,0,96.79,NaN,23,30

In [10]:
mdf

         mlink  date  hour  volume
0           76     1     0    23.0
1           77     1     0    35.0
2           78     1     0   101.0
3           79     1     0    45.0
4           80     1     0    46.0
5           81     1     0    29.0
6           82     1     0    42.0
7           83     1     0    42.0
8           84     1     0    36.0
9           85     1     0    28.0
10          86     1     0    28.0
11          87     1     0    16.0
12          88     1     0    16.0
13          89     1     0    18.0
14          90     1     0    23.0
15          91     1     0    25.0
16          92     1     0    10.0
17          93     1     0    10.0
18          94     1     0     7.0
19          95     1     0    11.0
20          96     1     0    12.0
21          97     1     0    13.0
22          98     1     0    11.0
23          99     1     0    16.0
24         100     1     0    10.0
25         101     1     0    14.0
26         102     1     0    14.0
27         103     1     0    19.0
28         104     1     0    24.0
29         105     1     0    45.0
...        ...   ...   ...     ...
2842530   1081    30    23    23.0
2842531   1082    30    23   144.0
2842532   1083    30    23   131.0
2842533   1084    30    23   130.0
2842534   1085    30    23   128.0
2842535   1086    30    23   127.0
2842536   1087    30    23   127.0
2842537   1088    30    23    72.0
2842538   1089    30    23    70.0
2842539   1090    30    23    70.0
2842540   1091    30    23    61.0
2842541   1092    30    23    69.0
2842542   1093    30    23    72.0
2842543   1094    30    23    42.0
2842544   1095    30    23    33.0
2842545   1096    30    23    16.0
2842546   1097    30    23    27.0
2842547   1098    30    23    22.0
2842548   1099    30    23    27.0
2842549   1100    30    23    28.0
2842550   1101    30    23    42.0
2842551   1102    30    23    41.0
2842552   1103    30    23    38.0
2842553   1104    30    23    41.0
2842554   1105    30    23    96.0
2842555   1106    30    23    99.0
2842556   1107    30    23    96.0
2842557   1108    30    23   120.0
2842558   1109    30    23   120.0
2842559   1110    30    23   125.0

[2842560 rows x 4 columns]

In [15]:
mdf[(mdf['mlink']==76) & (mdf['hour']==0)]

         mlink  date  hour  volume
0           76     1     0    23.0
987         76     1     0    26.0
1974        76     1     0    21.0
2961        76     1     0     8.0
94752       76     2     0    38.0
95739       76     2     0    25.0
96726       76     2     0    25.0
97713       76     2     0    13.0
189504      76     3     0    45.0
190491      76     3     0    67.0
191478      76     3     0    48.0
192465      76     3     0    45.0
284256      76     4     0    62.0
285243      76     4     0    61.0
286230      76     4     0    46.0
287217      76     4     0    44.0
379008      76     5     0    20.0
379995      76     5     0    15.0
380982      76     5     0    10.0
381969      76     5     0    12.0
473760      76     6     0    20.0
474747      76     6     0    13.0
475734      76     6     0    14.0
476721      76     6     0     8.0
568512      76     7     0    25.0
569499      76     7     0    14.0
570486      76     7     0    15.0
571473      76     7     0    20.0
663264      76     8     0    20.0
664251      76     8     0    30.0
...        ...   ...   ...     ...
2086518     76    23     0    20.0
2087505     76    23     0    22.0
2179296     76    24     0    66.0
2180283     76    24     0    58.0
2181270     76    24     0    51.0
2182257     76    24     0    45.0
2274048     76    25     0    69.0
2275035     76    25     0    63.0
2276022     76    25     0    58.0
2277009     76    25     0    50.0
2368800     76    26     0    55.0
2369787     76    26     0    45.0
2370774     76    26     0    28.0
2371761     76    26     0    23.0
2463552     76    27     0    20.0
2464539     76    27     0    18.0
2465526     76    27     0    13.0
2466513     76    27     0    21.0
2558304     76    28     0    29.0
2559291     76    28     0    22.0
2560278     76    28     0    21.0
2561265     76    28     0    26.0
2653056     76    29     0    30.0
2654043     76    29     0    24.0
2655030     76    29     0    18.0
2656017     76    29     0    15.0
2747808     76    30     0    38.0
2748795     76    30     0    41.0
2749782     76    30     0    26.0
2750769     76    30     0    25.0

[120 rows x 4 columns]

In [17]:
gmdf[(gmdf['mlink']==76) & (gmdf['hour']==0)]

     mlink  date  hour  volume
0       76     1     0    78.0
24      76     2     0   101.0
48      76     3     0   205.0
72      76     4     0   213.0
96      76     5     0    57.0
120     76     6     0    55.0
144     76     7     0    74.0
168     76     8     0    89.0
192     76     9     0    94.0
216     76    10     0   201.0
240     76    11     0   206.0
264     76    12     0    86.0
288     76    13     0    84.0
312     76    14     0    76.0
336     76    15     0    89.0
360     76    16     0    98.0
384     76    17     0   302.0
408     76    18     0   245.0
432     76    19     0    76.0
456     76    20     0    79.0
480     76    21     0    85.0
504     76    22     0    87.0
528     76    23     0   113.0
552     76    24     0   220.0
576     76    25     0   240.0
600     76    26     0   151.0
624     76    27     0    72.0
648     76    28     0    98.0
672     76    29     0    87.0
696     76    30     0   130.0

In [12]:
gmdf = mdf.groupby(['mlink','date','hour']).sum().reset_index()

In [13]:
avgmdf = gmdf.groupby(['mlink','hour']).mean() .reset_index()

In [31]:
avgmdf[1695]

KeyError: 1695

In [33]:
avgmdf

       mlink  hour  date       volume
0         76     0  15.5   126.366667
1         76     1  15.5    70.833333
2         76     2  15.5    44.166667
3         76     3  15.5    39.066667
4         76     4  15.5    73.433333
5         76     5  15.5   386.000000
6         76     6  15.5  1136.533333
7         76     7  15.5  1802.500000
8         76     8  15.5  2103.333333
9         76     9  15.5  1822.233333
10        76    10  15.5  1570.733333
11        76    11  15.5  1503.800000
12        76    12  15.5  1534.466667
13        76    13  15.5  1431.400000
14        76    14  15.5  1357.933333
15        76    15  15.5  1248.900000
16        76    16  15.5  1217.400000
17        76    17  15.5  1336.266667
18        76    18  15.5  1127.466667
19        76    19  15.5   699.166667
20        76    20  15.5   532.700000
21        76    21  15.5   469.666667
22        76    22  15.5   344.533333
23        76    23  15.5   208.233333
24        77     0  15.5   135.466667
25        77     1  15.5    75.366667
26        77     2  15.5    45.900000
27        77     3  15.5    35.100000
28        77     4  15.5    66.466667
29        77     5  15.5   326.466667
...      ...   ...   ...          ...
23658   1109    18  15.5  1470.966667
23659   1109    19  15.5   984.500000
23660   1109    20  15.5   775.766667
23661   1109    21  15.5   679.500000
23662   1109    22  15.5   514.566667
23663   1109    23  15.5   346.833333
23664   1110     0  15.5   331.866667
23665   1110     1  15.5   215.600000
23666   1110     2  15.5   136.200000
23667   1110     3  15.5   123.933333
23668   1110     4  15.5   355.066667
23669   1110     5  15.5   802.166667
23670   1110     6  15.5  1364.100000
23671   1110     7  15.5  1565.433333
23672   1110     8  15.5  1599.166667
23673   1110     9  15.5  1530.233333
23674   1110    10  15.5  1646.433333
23675   1110    11  15.5  1712.466667
23676   1110    12  15.5  1745.366667
23677   1110    13  15.5  1895.433333
23678   1110    14  15.5  2218.700000
23679   1110    15  15.5  2718.366667
23680   1110    16  15.5  3107.333333
23681   1110    17  15.5  2801.566667
23682   1110    18  15.5  1739.066667
23683   1110    19  15.5  1102.833333
23684   1110    20  15.5   901.866667
23685   1110    21  15.5   820.200000
23686   1110    22  15.5   610.500000
23687   1110    23  15.5   484.600000

[23688 rows x 4 columns]

In [36]:
mdf[(mdf['mlink']==146) & (mdf['hour']==15)]

         mlink  date  hour  volume
59290      146     1    15  1999.0
60277      146     1    15  2278.0
61264      146     1    15  2194.0
62251      146     1    15  2150.0
154042     146     2    15  2091.0
155029     146     2    15  2195.0
156016     146     2    15  2044.0
157003     146     2    15  2054.0
248794     146     3    15  1478.0
249781     146     3    15  1449.0
250768     146     3    15  1511.0
251755     146     3    15  1441.0
343546     146     4    15  1394.0
344533     146     4    15  1438.0
345520     146     4    15  1425.0
346507     146     4    15  1420.0
438298     146     5    15  1832.0
439285     146     5    15  2288.0
440272     146     5    15  2119.0
441259     146     5    15  2039.0
533050     146     6    15  1917.0
534037     146     6    15  2223.0
535024     146     6    15  1869.0
536011     146     6    15  2003.0
627802     146     7    15  2004.0
628789     146     7    15  2226.0
629776     146     7    15  2173.0
630763     146     7    15  2091.0
722554     146     8    15  2041.0
723541     146     8    15  2108.0
...        ...   ...   ...     ...
2145808    146    23    15  2028.0
2146795    146    23    15  2051.0
2238586    146    24    15  1325.0
2239573    146    24    15  1415.0
2240560    146    24    15  1329.0
2241547    146    24    15  1276.0
2333338    146    25    15  1316.0
2334325    146    25    15  1329.0
2335312    146    25    15  1277.0
2336299    146    25    15  1211.0
2428090    146    26    15  1269.0
2429077    146    26    15  1266.0
2430064    146    26    15  1281.0
2431051    146    26    15  1248.0
2522842    146    27    15  1883.0
2523829    146    27    15  2075.0
2524816    146    27    15  2036.0
2525803    146    27    15  2025.0
2617594    146    28    15  1981.0
2618581    146    28    15  2193.0
2619568    146    28    15  2001.0
2620555    146    28    15  1850.0
2712346    146    29    15  2035.0
2713333    146    29    15  2131.0
2714320    146    29    15  2029.0
2715307    146    29    15  1885.0
2807098    146    30    15  2013.0
2808085    146    30    15  2071.0
2809072    146    30    15  1901.0
2810059    146    30    15  1749.0

[120 rows x 4 columns]

In [35]:
avgmdf.sort_values("volume",ascending = False)

       mlink  hour  date       volume
1695     146    15  15.5  7455.200000
1696     146    16  15.5  6976.066667
1694     146    14  15.5  6747.800000
1697     146    17  15.5  6736.900000
1600     142    16  15.5  6619.400000
1648     144    16  15.5  6619.400000
1624     143    16  15.5  6619.400000
1623     143    15  15.5  6615.266667
1599     142    15  15.5  6615.266667
1647     144    15  15.5  6615.266667
15824    740     8  15.5  6472.500000
1400     134     8  15.5  6472.500000
1649     144    17  15.5  6464.300000
1625     143    17  15.5  6464.300000
1601     142    17  15.5  6464.300000
15800    739     8  15.5  6448.033333
2792     192     8  15.5  6320.400000
1863     153    15  15.5  6279.666667
1671     145    15  15.5  6272.700000
15801    739     9  15.5  6131.200000
1719     147    15  15.5  6124.033333
2793     192     9  15.5  6115.433333
15807    739    15  15.5  6099.300000
1401     134     9  15.5  6087.966667
15825    740     9  15.5  6087.966667
2840     194     8  15.5  6087.166667
15804    739    12  15.5  6080.366667
1672     145    16  15.5  6066.833333
1407     134    15  15.5  6060.866667
15831    740    15  15.5  6060.866667
...      ...   ...   ...          ...
19559    936    23  15.5     6.333333
11354    550     2  15.5     6.300000
11378    551     2  15.5     6.300000
18263    882    23  15.5     6.266667
19247    923    23  15.5     6.166667
10514    515     2  15.5     6.166667
6169     334     1  15.5     6.133333
1369     133     1  15.5     6.033333
18242    882     2  15.5     5.866667
5113     290     1  15.5     5.633333
5089     289     1  15.5     5.633333
12771    609     3  15.5     5.633333
19105    918     1  15.5     5.600000
19129    919     1  15.5     5.600000
10515    515     3  15.5     5.533333
12772    609     4  15.5     5.400000
5185     293     1  15.5     5.100000
5161     292     1  15.5     5.100000
6170     334     2  15.5     4.800000
1370     133     2  15.5     4.366667
19106    918     2  15.5     4.233333
19130    919     2  15.5     4.233333
1371     133     3  15.5     4.200000
19224    923     0  15.5     3.966667
19227    923     3  15.5     3.533333
19225    923     1  15.5     2.833333
19538    936     2  15.5     2.766667
19536    936     0  15.5     2.233333
19226    923     2  15.5     2.166667
19537    936     1  15.5     1.200000

[23688 rows x 4 columns]

In [ ]:
sdf = silodf[['mlink','Hour','MATSIM volumes']]
sdf.columns = ['mlink','hour','volume']

In [ ]:
tem = np.array(sdf[(sdf['mlink'] == 76) & (sdf['hour'] == 12)].volume)

In [ ]:
np.sort(tem)

In [ ]:
resdict = {
    'mlink':[],
    'hour':[],
    'vol':[]
}
mlinklist = np.unique(sdf.mlink)
for ml in tqdm_notebook(mlinklist):
    for hour in range(1,25):
        vollist = np.array(sdf[(sdf['mlink'] == ml) & (sdf['hour'] == hour)].volume)
        vollist  = np.sort(vollist)
        volen = len(vollist)
        tvol = 0
        if volen >=3:
            tvol = vollist[volen//2]
        else:
            tvol = vollist[-1]
        resdict['mlink'].append(ml)
        resdict['hour'].append(hour)
        resdict['vol'].append(tvol)

In [ ]:
gsdf = pd.DataFrame(resdict)

In [ ]:
gsdf

In [ ]:
resdf = gsdf.merge(avgmdf, on=["mlink","hour"])

In [ ]:
resdf

In [ ]:
resdf = resdf[['mlink','hour','vol','volume']]
resdf.columns = ['mlink','hour','matvol','vol']
resdf = resdf[(resdf['matvol']!=0)& (resdf['vol']!=0)]

In [ ]:
resdf['proportion'] = resdf['vol'] / resdf['matvol']

In [ ]:
resdf

In [ ]:
resdf.to_csv('./data/matsim-mlink-compare.csv')

In [ ]:
mpl.rcParams['figure.figsize'] = [12.0, 8.0]
mpl.rcParams['figure.dpi'] = 300

In [ ]:
plt.scatter(resdf.matvol, resdf.vol,s=1)

In [ ]:
peak = resdf[((resdf["hour"] <= 9) & (resdf["hour"]>=7)) | ( (resdf["hour"] <= 18) & (resdf["hour"]>=16) )]

In [ ]:
offpeak= resdf[((resdf["hour"] < 7) | (resdf["hour"]>9)) & ( (resdf["hour"] < 16) | (resdf["hour"]>18) )]

In [ ]:
offpeaklowvol = offpeak[offpeak['matvol']<100]

In [ ]:
plt.scatter(offpeak.matvol, offpeak.vol,s=1)

In [ ]:
peakhvol = peak[(peak['matvol']>50)]
plt.scatter(peakhvol.matvol, peakhvol.vol,s=1)

In [ ]:
np.square(np.subtract(peakhvol.matvol, peakhvol.vol)).mean()

In [ ]:
np.square(np.subtract(offpeak.matvol, offpeak.vol)).mean()